### ISSUE TITLE
Refactor to not use event emitter

### ISSUE THREAD

**Issue by joachimbulow** [Unleash/unleash_proxy_client_flutter#51]
### Describe the feature request

The event emitter pattern is tedious to work with and debug.

Furthermore, if an error occurs, there is seemingly only a single event emitted, and it is simply `null`.

I think you can provide a better dev experience than this.

### Background

Had to setup simple A/B testing system, connecting to our edge proxy. 

No way to let my client time out, no way to await its response, only being able to react to events I was left with a single `null` event as an immediate debugging measure.

Thought you would like to be informed about this:)

Loving your product in general tho, keep it up

### Solution suggestions

Just provide the option for a single manual async `client connect` functionality. With corresponding errors.
Puts the power in the developers hands.

**Comment by kwasniew** [comment]
Hey @joachimbulow . Thanks for reaching out to us. 

This frontend SDK was modelled after another frontend SDK https://github.com/Unleash/unleash-proxy-client-js. The idea was to keep the API surface area of the SDKs consistent.
Under the hood Unleash is refetching the flags on a schedule so the async problem we’re solving is a stream of requests over time. Event emitter is one abstraction for that, the other being something like observables.
Having async/promise/future abstraction to connect at startup would not solve the issue of subsequent requests failing. 

Regarding the custom HTTP behaviour adjustments we deliberately made this client composable so that you can inject any HTTP setup in the UnleashClient constructor. 
You can find some examples in our tests: https://github.com/Unleash/unleash_proxy_client_flutter/blob/main/test/unleash_proxy_client_flutter_test.dart#L95

You can swap default implementation: https://github.com/Unleash/unleash_proxy_client_flutter/blob/main/lib/http_toggle_client.dart

With sth like ```
Future<http.Response> get(http.Request request) {
  return http.get(request.url, headers: request.headers).timeout(Duration(seconds: 10));
}
```


And finally regarding the null error that you got, could you create a reproduction unit test so that we can take a look together. 
We have a test showing that error should not be swallowed: https://github.com/Unleash/unleash_proxy_client_flutter/blob/main/test/unleash_proxy_client_flutter_test.dart#L291
but maybe we missed something important.

**Comment by joachimbulow** [comment]
Hi, 

Thanks for the thorough reply.
We ended up using a `completer` which would fulfill / complete upon the `ready` signal being achieved.
So I guess the implementation ended up kind of smooth - would just be nice with a way to `await` the initial readiness state.

I suppose I could pretty simply add a PR for that. Might look into that if I get time.

Thanks again, have a good one
